# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "fedora/beta-26-cloud-base"
  config.vm.box_version = "1.4"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf -y install git python3 python3-pip;

    sudo pip3 install selenium
    sudo pip3 install beautifulsoup4
  SHELL
end
